// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: cluster/replication.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_cluster_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_cluster_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicationRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failure       bool                   `protobuf:"varint,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_cluster_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_cluster_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationResponse) GetFailure() bool {
	if x != nil {
		return x.Failure
	}
	return false
}

var File_cluster_replication_proto protoreflect.FileDescriptor

const file_cluster_replication_proto_rawDesc = "" +
	"\n" +
	"\x19cluster/replication.proto\x12\acluster\"<\n" +
	"\x12ReplicationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"I\n" +
	"\x13ReplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\afailure\x18\x02 \x01(\bR\afailure2\\\n" +
	"\x12ReplicationService\x12F\n" +
	"\tReplicate\x12\x1b.cluster.ReplicationRequest\x1a\x1c.cluster.ReplicationResponseB\x13Z\x11/internal/clusterb\x06proto3"

var (
	file_cluster_replication_proto_rawDescOnce sync.Once
	file_cluster_replication_proto_rawDescData []byte
)

func file_cluster_replication_proto_rawDescGZIP() []byte {
	file_cluster_replication_proto_rawDescOnce.Do(func() {
		file_cluster_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_replication_proto_rawDesc), len(file_cluster_replication_proto_rawDesc)))
	})
	return file_cluster_replication_proto_rawDescData
}

var file_cluster_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cluster_replication_proto_goTypes = []any{
	(*ReplicationRequest)(nil),  // 0: cluster.ReplicationRequest
	(*ReplicationResponse)(nil), // 1: cluster.ReplicationResponse
}
var file_cluster_replication_proto_depIdxs = []int32{
	0, // 0: cluster.ReplicationService.Replicate:input_type -> cluster.ReplicationRequest
	1, // 1: cluster.ReplicationService.Replicate:output_type -> cluster.ReplicationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cluster_replication_proto_init() }
func file_cluster_replication_proto_init() {
	if File_cluster_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_replication_proto_rawDesc), len(file_cluster_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_replication_proto_goTypes,
		DependencyIndexes: file_cluster_replication_proto_depIdxs,
		MessageInfos:      file_cluster_replication_proto_msgTypes,
	}.Build()
	File_cluster_replication_proto = out.File
	file_cluster_replication_proto_goTypes = nil
	file_cluster_replication_proto_depIdxs = nil
}
