// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: reviews.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewCommand_CommandType int32

const (
	ReviewCommand_UNKNOWN    ReviewCommand_CommandType = 0
	ReviewCommand_ADD_REVIEW ReviewCommand_CommandType = 1
)

// Enum value maps for ReviewCommand_CommandType.
var (
	ReviewCommand_CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADD_REVIEW",
	}
	ReviewCommand_CommandType_value = map[string]int32{
		"UNKNOWN":    0,
		"ADD_REVIEW": 1,
	}
)

func (x ReviewCommand_CommandType) Enum() *ReviewCommand_CommandType {
	p := new(ReviewCommand_CommandType)
	*p = x
	return p
}

func (x ReviewCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_reviews_proto_enumTypes[0].Descriptor()
}

func (ReviewCommand_CommandType) Type() protoreflect.EnumType {
	return &file_reviews_proto_enumTypes[0]
}

func (x ReviewCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewCommand_CommandType.Descriptor instead.
func (ReviewCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{0, 0}
}

type ReviewCommand struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Type     ReviewCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=cluster.ReviewCommand_CommandType" json:"type,omitempty"`
	RecipeId string                    `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	ReviewId      string                    `protobuf:"bytes,3,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Stars         float32                   `protobuf:"fixed32,4,opt,name=stars,proto3" json:"stars,omitempty"`
	Title         string                    `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                    `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCommand) Reset() {
	*x = ReviewCommand{}
	mi := &file_reviews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCommand) ProtoMessage() {}

func (x *ReviewCommand) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCommand.ProtoReflect.Descriptor instead.
func (*ReviewCommand) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewCommand) GetType() ReviewCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ReviewCommand_UNKNOWN
}

func (x *ReviewCommand) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *ReviewCommand) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *ReviewCommand) GetStars() float32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *ReviewCommand) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReviewCommand) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type AddReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Stars         float32                `protobuf:"fixed32,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewRequest) Reset() {
	*x = AddReviewRequest{}
	mi := &file_reviews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewRequest) ProtoMessage() {}

func (x *AddReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewRequest.ProtoReflect.Descriptor instead.
func (*AddReviewRequest) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{1}
}

func (x *AddReviewRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *AddReviewRequest) GetStars() float32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *AddReviewRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddReviewRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_reviews_proto protoreflect.FileDescriptor

const file_reviews_proto_rawDesc = "" +
	"\n" +
	"\rreviews.proto\x12\acluster\"\xed\x01\n" +
	"\rReviewCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".cluster.ReviewCommand.CommandTypeR\x04type\x12\x1b\n" +
	"\trecipe_id\x18\x02 \x01(\tR\brecipeId\x12\x1b\n" +
	"\treview_id\x18\x03 \x01(\tR\breviewId\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x02R\x05stars\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"*\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"ADD_REVIEW\x10\x01\"o\n" +
	"\x10AddReviewRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x02R\x05stars\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04bodyB\x13Z\x11/internal/clusterb\x06proto3"

var (
	file_reviews_proto_rawDescOnce sync.Once
	file_reviews_proto_rawDescData []byte
)

func file_reviews_proto_rawDescGZIP() []byte {
	file_reviews_proto_rawDescOnce.Do(func() {
		file_reviews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)))
	})
	return file_reviews_proto_rawDescData
}

var file_reviews_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reviews_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reviews_proto_goTypes = []any{
	(ReviewCommand_CommandType)(0), // 0: cluster.ReviewCommand.CommandType
	(*ReviewCommand)(nil),          // 1: cluster.ReviewCommand
	(*AddReviewRequest)(nil),       // 2: cluster.AddReviewRequest
}
var file_reviews_proto_depIdxs = []int32{
	0, // 0: cluster.ReviewCommand.type:type_name -> cluster.ReviewCommand.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reviews_proto_init() }
func file_reviews_proto_init() {
	if File_reviews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reviews_proto_goTypes,
		DependencyIndexes: file_reviews_proto_depIdxs,
		EnumInfos:         file_reviews_proto_enumTypes,
		MessageInfos:      file_reviews_proto_msgTypes,
	}.Build()
	File_reviews_proto = out.File
	file_reviews_proto_goTypes = nil
	file_reviews_proto_depIdxs = nil
}
