services:
  node1:
    image: jjiang0595/raft-node:v1.0.0
    ports:
      - "8080:8080"
      - "6000:6000"
    volumes:
      - ./config/docker/config-node1.yaml:/app/config.yaml
      - ./node_data:/app/data
    environment:
      RAFT_NODE_ID: node1
      RAFT_NODE_HTTP_PORT: 8080
      RAFT_NODE_GRPC_PORT: 6000
      RAFT_NODE_DATA_DIR: /app/data/node1
    command: ["./server", "--config", "/app/config.yaml"]
  node2:
    image: jjiang0595/raft-node:v1.0.0
    ports:
      - "8081:8081"
      - "6001:6001"
    volumes:
      - ./config/docker/config-node2.yaml:/app/config.yaml
      - ./node_data:/app/data
    environment:
      RAFT_NODE_ID: node2
      RAFT_NODE_HTTP_PORT: 8081
      RAFT_NODE_GRPC_PORT: 6001
      RAFT_NODE_DATA_DIR: /app/data/node2
    command: ["./server", "--config", "/app/config.yaml"]
  node3:
    image: jjiang0595/raft-node:v1.0.0
    ports:
      - "8082:8082"
      - "6002:6002"
    volumes:
      - ./config/docker/config-node3.yaml:/app/config.yaml
      - ./node_data:/app/data
    environment:
      RAFT_NODE_ID: node3
      RAFT_NODE_HTTP_PORT: 8082
      RAFT_NODE_GRPC_PORT: 6002
      RAFT_NODE_DATA_DIR: /app/data/node3
    command: ["./server", "--config", "/app/config.yaml"]
