apiVersion: v1
kind: PersistentVolume
metadata:
  name: raft-data-2
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "raft-kv-store.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: raft-volume-2
  claimRef:
    name: raft-data-raft-cluster-2
    namespace: {{ .Release.Namespace }}
