apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-data-raft-cluster-0
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "raft-kv-store.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi