#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: raft-cluster
#  labels:
#    app: raft
#spec:
#  serviceName: raft-service
#  replicas: 3
#  selector:
#    matchLabels:
#      app: raft
#  template:
#    metadata:
#      labels:
#        app: raft
#    spec:
#      imagePullSecrets:
#      - name: raft-registry-secret
#      containers:
#      - name: raft-node
#        image: jjiang0595/raft-node:v1.0.0
#        imagePullPolicy: IfNotPresent
#        ports:
#          - containerPort: 8080
#          - containerPort: 6000
#        volumeMounts:
#          - name: config-volume
#            mountPath: /etc/config
#            readOnly: true
#          - name: raft-storage
#            mountPath: /app/data
#        env:
#          - name: RAFT_NODE_ID
#            valueFrom:
#              fieldRef:
#                fieldPath: metadata.name
#          - name: RAFT_NODE_ADDRESS
#            value: "$(RAFT_NODE_ID).raft-service"
#          - name: RAFT_NODE_HTTP_PORT
#            value: "8080"
#          - name: RAFT_NODE_GRPC_PORT
#            value: "6000"
#          - name: RAFT_NODE_DATA_DIR
#            value: "/app/data"
#        command: ["/app/server"]
#        args:
#        - --config=/etc/config/config.yaml
#      volumes:
#      - name: config-volume
#        configMap:
#          name: raft-config-map
#          items:
#          - key: config.yaml
#            path: config.yaml
#      - name: raft-storage
#        persistentVolumeClaim:
#          claimName: raft-data-raft-cluster-0
#  volumeClaimTemplates:
#  - metadata:
#      name: raft-data
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      volumeMode: Filesystem
#      storageClassName: longhorn
#      resources:
#        requests:
#          storage: 1Gi