node:
  id: node2
  address: 127.0.0.1
  http_port: 8081
  grpc_port: 6001
  data_dir: ./node_data/node2
cluster:
  peers:
    - id: node1
      address: 127.0.0.1
      http_port: 8080
      grpc_port: 6000
      data_dir: ./node_data/node1
    - id: node2
      address: 127.0.0.1
      http_port: 8081
      grpc_port: 6001
    - id: node3
      address: 127.0.0.1
      http_port: 8082
      grpc_port: 6002
